services:
  web:
    build: .
    ports:
      - "3080:3000"
    environment:
      - TZ=Asia/Taipei
    #volumes:
      #- .:/app
      #- /app/node_modules
    env_file:
      - .env
    restart: always
