services:
  api:
    build: .
    ports:
      - "4000:8000"
    environment:
      - TZ=Asia/Taipei
    env_file:
      - .env
    volumes:
      - .:/app
      - ./hf_cache:/app/hf_cache
    restart: always